export const SEED_TEXTS = [
  {
    title: "子路、曾皙、冉有、公西华侍坐",
    author: "孔子",
    dynasty: "先秦",
    source: "《论语·先进》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 1,
    content: "",
    isBuiltin: true,
  },
  {
    title: "齐桓晋文之事",
    author: "孟子",
    dynasty: "先秦",
    source: "《孟子·梁惠王上》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 2,
    content: "",
    isBuiltin: true,
  },
  {
    title: "庖丁解牛",
    author: "庄子",
    dynasty: "先秦",
    source: "《庄子·养生主》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 3,
    content: "",
    isBuiltin: true,
  },
  {
    title: "烛之武退秦师",
    author: "左丘明",
    dynasty: "先秦",
    source: "《左传·僖公三十年》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 4,
    content: "",
    isBuiltin: true,
  },
  {
    title: "鸿门宴",
    author: "司马迁",
    dynasty: "汉",
    source: "《史记·项羽本纪》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 5,
    content: "",
    isBuiltin: true,
  },
  {
    title: "谏逐客书",
    author: "李斯",
    dynasty: "秦",
    source: "",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 6,
    content: "",
    isBuiltin: true,
  },
  {
    title: "谏太宗十思疏",
    author: "魏征",
    dynasty: "唐",
    source: "",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 7,
    content: "",
    isBuiltin: true,
  },
  {
    title: "答司马谏议书",
    author: "王安石",
    dynasty: "宋",
    source: "",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 8,
    content: "",
    isBuiltin: true,
  },
  {
    title: "阿房宫赋",
    author: "杜牧",
    dynasty: "唐",
    source: "",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 9,
    content: "",
    isBuiltin: true,
  },
  {
    title: "六国论",
    author: "苏洵",
    dynasty: "宋",
    source: "",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 10,
    content: "",
    isBuiltin: true,
  },
  {
    title: "促织",
    author: "蒲松龄",
    dynasty: "清",
    source: "《聊斋志异》",
    volumeId: "required_2",
    textType: "wenyanwen",
    textOrder: 11,
    content: "",
    isBuiltin: true,
  },
  // 必修下 古诗词诵读
  { title: "登岳阳楼", author: "杜甫", dynasty: "唐", source: "", volumeId: "required_2", textType: "gushici", textOrder: 11, content: "", isBuiltin: true },
  { title: "桂枝香·金陵怀古", author: "王安石", dynasty: "宋", source: "", volumeId: "required_2", textType: "gushici", textOrder: 12, content: "", isBuiltin: true },
  { title: "念奴娇·过洞庭", author: "张孝祥", dynasty: "宋", source: "", volumeId: "required_2", textType: "gushici", textOrder: 13, content: "", isBuiltin: true },
  { title: "游园", author: "汤显祖", dynasty: "明", source: "《牡丹亭》", volumeId: "required_2", textType: "gushici", textOrder: 14, content: "", isBuiltin: true },
  // 选择性必修上
  { title: "无衣", author: "佚名", dynasty: "先秦", source: "《诗经·秦风》", volumeId: "selective_1", textType: "gushici", textOrder: 1, content: "", isBuiltin: true },
  { title: "春江花月夜", author: "张若虚", dynasty: "唐", source: "", volumeId: "selective_1", textType: "gushici", textOrder: 2, content: "", isBuiltin: true },
  { title: "将进酒", author: "李白", dynasty: "唐", source: "", volumeId: "selective_1", textType: "gushici", textOrder: 3, content: "", isBuiltin: true },
  { title: "江城子·乙卯正月二十日夜记梦", author: "苏轼", dynasty: "宋", source: "", volumeId: "selective_1", textType: "gushici", textOrder: 4, content: "", isBuiltin: true },
  // 选择性必修中 文言文
  { title: "屈原列传", author: "司马迁", dynasty: "汉", source: "《史记》", volumeId: "selective_2", textType: "wenyanwen", textOrder: 1, content: "", isBuiltin: true },
  { title: "苏武传", author: "班固", dynasty: "汉", source: "《汉书》", volumeId: "selective_2", textType: "wenyanwen", textOrder: 2, content: "", isBuiltin: true },
  { title: "过秦论", author: "贾谊", dynasty: "汉", source: "", volumeId: "selective_2", textType: "wenyanwen", textOrder: 3, content: "", isBuiltin: true },
  { title: "五代史伶官传序", author: "欧阳修", dynasty: "宋", source: "", volumeId: "selective_2", textType: "wenyanwen", textOrder: 4, content: "", isBuiltin: true },
  // 选择性必修中 古诗词
  { title: "燕歌行（并序）", author: "高适", dynasty: "唐", source: "", volumeId: "selective_2", textType: "gushici", textOrder: 5, content: "", isBuiltin: true },
  { title: "李凭箜篌引", author: "李贺", dynasty: "唐", source: "", volumeId: "selective_2", textType: "gushici", textOrder: 6, content: "", isBuiltin: true },
  { title: "锦瑟", author: "李商隐", dynasty: "唐", source: "", volumeId: "selective_2", textType: "gushici", textOrder: 7, content: "", isBuiltin: true },
  { title: "书愤", author: "陆游", dynasty: "宋", source: "", volumeId: "selective_2", textType: "gushici", textOrder: 8, content: "", isBuiltin: true },
  // 选择性必修下 文言文
  { title: "陈情表", author: "李密", dynasty: "晋", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 1, content: "", isBuiltin: true },
  { title: "项脊轩志", author: "归有光", dynasty: "明", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 2, content: "", isBuiltin: true },
  { title: "兰亭集序", author: "王羲之", dynasty: "晋", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 3, content: "", isBuiltin: true },
  { title: "归去来兮辞并序", author: "陶渊明", dynasty: "晋", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 4, content: "", isBuiltin: true },
  { title: "种树郭橐驼传", author: "柳宗元", dynasty: "唐", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 5, content: "", isBuiltin: true },
  { title: "石钟山记", author: "苏轼", dynasty: "宋", source: "", volumeId: "selective_3", textType: "wenyanwen", textOrder: 6, content: "", isBuiltin: true },
  // 选择性必修下 古诗词
  { title: "氓", author: "佚名", dynasty: "先秦", source: "《诗经·卫风》", volumeId: "selective_3", textType: "gushici", textOrder: 7, content: "", isBuiltin: true },
  { title: "离骚（节选）", author: "屈原", dynasty: "先秦", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 8, content: "", isBuiltin: true },
  { title: "孔雀东南飞并序", author: "佚名", dynasty: "汉", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 9, content: "", isBuiltin: true },
  { title: "蜀道难", author: "李白", dynasty: "唐", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 10, content: "", isBuiltin: true },
  { title: "蜀相", author: "杜甫", dynasty: "唐", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 11, content: "", isBuiltin: true },
  { title: "望海潮（东南形胜）", author: "柳永", dynasty: "宋", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 12, content: "", isBuiltin: true },
  { title: "扬州慢（淮左名都）", author: "姜夔", dynasty: "宋", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 13, content: "", isBuiltin: true },
  { title: "拟行路难（其四）", author: "鲍照", dynasty: "南北朝", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 14, content: "", isBuiltin: true },
  { title: "客至", author: "杜甫", dynasty: "唐", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 15, content: "", isBuiltin: true },
  { title: "登快阁", author: "黄庭坚", dynasty: "宋", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 16, content: "", isBuiltin: true },
  { title: "临安春雨初霁", author: "陆游", dynasty: "宋", source: "", volumeId: "selective_3", textType: "gushici", textOrder: 17, content: "", isBuiltin: true },
]
